### ISSUE TITLE
能不能发下安装包，pc&Android 

### ISSUE THREAD

**Issue by kaiser20106** [Chemical118/TwomonSETool#1]

**Comment by Chemical118** [comment]
First of all, thank you for visiting my Github. This was my goal to check that the three 'hid-compliant touch screen' used by 'Twomon SE' forcibly widen the gap between icons of taskbar and create a batch file that can be controlled to solve this problem. Therefore, there is no installation file. Also, when you use this, you have to modify the [Hardware ID](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/hardware-ids) of the three devices you mentioned earlier. I added 'C:\ProgramData\Microsoft\Windows\StartMenu\Programs' to indicate the shortcut to the batch file to use in the Windows10 search 
非常感谢你的关心。zhku-20106 :)
